export const colors = [
  { name: "Berry Red", code: "#701f28" },
  { name: "Red", code: "#FF0000" },
  { name: "Orange", code: "#FFA500" },
  { name: "Yellow", code: "#FFFF00" },
  { name: "Olive Green", code: "#808000" },
  { name: "Lime Green", code: "#32CD32" },
  { name: "Green", code: "#00FF00" },
  { name: "Mint Green", code: "#3EB489" },
  { name: "Teal", code: "#006D5B" },
  { name: "Sky Blue", code: "#87CEEB" },
  { name: "Light Blue", code: "#ADD8E6" },
  { name: "Blue", code: "#0000FF" },
  { name: "Grape", code: "#6f2da8" },
  { name: "Violet", code: "#8F00FF" },
  { name: "Lavender", code: "#E6E6FA" },
  { name: "Magenta", code: "#FF00FF" },
  { name: "Salmon", code: "#FA8072" },
  { name: "Charcoal", code: "#36454F" },
  { name: "Grey", code: "#808080" },
  { name: "Taupe", code: "#483C32" },
];
